ScheduleControl/ScheduleControl.WebUI/Models/ErrorViewModel.cs
namespace ScheduleControl.WebUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ScheduleControl/ScheduleControl.WebUI/ViewModels/AuthViewModel.cs
using ScheduleControl.Entities.Dtos.Account;

namespace ScheduleControl.WebUI.ViewModels
{
    public class AuthViewModel
    {
        public UserForLoginDto UserForLoginDto { get; set; }
        public UserForRegisterDto UserForRegisterDto { get; set; }
    }
}

ScheduleControl/ScheduleControl.WebUI/ViewModels/CashboxInputViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ScheduleControl.WebUI.ViewModels
{
    public class CashboxInputViewModel
    {
        public  List<SelectListItem> CashTypeItemList { get; set; }
        public decimal TotalQuantity { get; set; }
    }
}

ScheduleControl/ScheduleControl.WebUI/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using ScheduleControl.BackgroundJob.Schedules;
using ScheduleControl.Business.Abstract.Auth;
using ScheduleControl.Entities.Dtos.Account;
using ScheduleControl.WebUI.ViewModels;
using System;

namespace ScheduleControl.WebUI.Controllers
{
    public class AccountController : Controller
    {
        private readonly IAuthService _authService;

        public AccountController(IAuthService authService)
        {
            _authService = authService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("Register")]
        public IActionResult Register()
        {
            var data = new AuthViewModel() { UserForLoginDto = new UserForLoginDto(), UserForRegisterDto = new UserForRegisterDto() };
            return PartialView("_Register",data);
        }

        [HttpPost("Register")]
        [Obsolete]
        public IActionResult Register(AuthViewModel authViewModel)
        {
            var user = _authService.Register(authViewModel.UserForRegisterDto);
            DelayedJobs.SendMailRegisterJobs(user.UserId);
            return RedirectToAction("Index", "Home");
        }




        [HttpGet("Login")]
        public PartialViewResult Login()
        {
            //return PartialView("Login");
            return PartialView("Login", new AuthViewModel());
        }

        [HttpPost("Login")]
        public IActionResult Login(AuthViewModel authViewModel)
        {
            var user = _authService.Login(authViewModel.UserForLoginDto);
            return RedirectToAction("Index", "Home");
        }

        //[HttpGet("UserRegisterCheck")]
        public IActionResult UserRegisterCheck(string reqUrl)
        {
            if (string.IsNullOrEmpty(reqUrl))
                return RedirectToAction("Error", "Home");
            _authService.UserActivatedRegister(reqUrl);
            return RedirectToAction("Index", "Home");
        }
    }
}

ScheduleControl/ScheduleControl.WebUI/Controllers/CashboxController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ScheduleControl.BackgroundJob.Schedules;
using ScheduleControl.Business.Abstract;
using ScheduleControl.Entities.Dtos.Cashbox;
using ScheduleControl.Entities.Models;
using ScheduleControl.WebUI.ViewModels;
using System;
using System.Collections.Generic;

namespace ScheduleControl.WebUI.Controllers
{
    public class CashboxController : Controller
    {
        private readonly ICashboxService _cashboxService;
        private readonly ICashTypeService _cashTypeService;

        public CashboxController(ICashboxService cashboxService, ICashTypeService cashTypeService)
        {
            _cashboxService = cashboxService;
            _cashTypeService = cashTypeService;
        }

        public IActionResult Index()
        {
            return View(new CashboxInputViewModel());
        }

        [HttpGet]
        public IActionResult CashInsert()
        {
            var model = GetViewModelData();
            return View(model);
        }

        [Obsolete]
        [HttpPost("CashInsert")]
        public IActionResult CashInsert(CashboxInputDto cashboxInputDto)
        {
            _cashboxService.Insert(new Cashbox { 
                                                  CashTypeId = cashboxInputDto.CashTypeItemList[0], 
                                                  TotalQuantity = cashboxInputDto.TotalQuantity 
                                                }
                                   );
            
            FireAndForgetJobs.GetCurrencyJob();
            return View("CashInsert", GetViewModelData());
        }

        private CashboxInputViewModel GetViewModelData()
        {
            var typesData = _cashTypeService.GetAll();
            List<SelectListItem> data = new List<SelectListItem>();
            foreach (var item in typesData)
            {
                data.Add(new SelectListItem { Text = item.CashTypeName, Value = item.CashTypeId.ToString(), Selected = false });
            }
            return new CashboxInputViewModel { CashTypeItemList = data, TotalQuantity = 0 };
        }
    }
}

ScheduleControl/ScheduleControl.WebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ScheduleControl.BackgroundJob.Schedules;
using ScheduleControl.Entities.Dtos.Mail;
using ScheduleControl.WebUI.Models;
using System;
using System.Diagnostics;

namespace ScheduleControl.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [Obsolete]
        public IActionResult Index()
        {
            //bir takım işlemler ve sponrasında mail tetikleniyor
            //FireAndForgetJobs.SendMailJob(new MailMessageDto {
            //    To = "mailadresiniz@gmail.com",
            //    Subject = "Kullanıcı Register Islemi Kontrol",
            //    From = "appsettingdosyasındanokunanadres@gmail.com",
            //    Body="Icerik"
            //}); 
            return View();
        }
        [HttpGet]
        public IActionResult HangfireAbout()
        {
            // bir takım işlemler ve sponrasında mail tetikleniyor
            //FireAndForgetJobs.CheckCurrencyDataRefresh();
            //DelayedJobs.SendMailJobs();
            return View();
        }



        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ScheduleControl/ScheduleControl.WebUI/Views/Cashbox/CashInsert.cshtml
@model ScheduleControl.WebUI.ViewModels.CashboxInputViewModel
@{
    ViewData["Title"] = "CashInsert";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Cash İşlem Sayfası</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CashInsert"  method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="@Model.CashTypeItemList" class="control-label"></label>

                @*@Html.DropDownList("Cash Types", Model.CashTypeItemList)*@
                @*@Html.DropDownList("CountryList",  Model.CashTypeItemList, "Seçiniz",  new { @class="form-control" })*@
                @Html.DropDownListFor(d => d.CashTypeItemList, Model.CashTypeItemList, "Seçiniz", new { @class = "form-control" })
                @*<input asp-for="@ModelCashTypeItemList" class="form-control" />
        <span asp-validation-for="CaseTypeId" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <label asp-for="TotalQuantity" class="control-label"></label>
                <input asp-for="TotalQuantity" class="form-control" />
                <span asp-validation-for="TotalQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ScheduleControl/ScheduleControl.WebUI/Views/Home/HangfireAbout.cshtml
@{
    ViewData["Title"] = "HangfireAbout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<iframe src="https://medium.com/@@ademolguner" style="width:100%; height:6000px; border:none; scrollbar-base-color:transparent;"></iframe>

ScheduleControl/ScheduleControl.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ScheduleControl/ScheduleControl.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ScheduleControl.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ScheduleControl.WebUI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="javascript:();" onclick="Registered();">Register</a>
                            @*data-toggle="modal" data-target="#loginModal"*@
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Cashbox" asp-action="CashInsert">Cash Operation</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/ademolgunerhangfire">Hangfire</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ScheduleControl.WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="false">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="loginModalLabel">Authentication Operation</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="ModalPopupAuth">
                    
                </div>
                <div class="modal-footer">
                    @*<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Save changes</button>*@
                </div>
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

<script type="text/javascript">


    function Registered() {
       // debugger;
        var url = '@Url.Action("Register", "Account")';
        //url += '/?Id=' + ortakId;
        $('#loginModal').modal('show').find('#ModalPopupAuth').load(url);

    }
     
</script>
</body>
</html>